backend:
  name: github
  repo: mn3ff20/novel-site
  branch: main
  open_authoring: true
  auth_scope: repo
  auth_endpoint: https://github.com/login/oauth/authorize
  api_root: https://api.github.com
  base_url: https://github.com/login/oauth/authorize
  auth_type: implicit
  client_id: YOUR_CLIENT_ID  Ov23li1ircDrH2E9WNKd
