backend:
  name: github
  repo: YOUR_USERNAME/novel-site
  branch: main

media_folder: "novels/uploads"
public_folder: "/novels/uploads"

collections:
  - name: "novels"
    label: "روايات"
    folder: "novels"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان الرواية", name: "title", widget: "string" }
      - { label: "نبذة", name: "description", widget: "text" }
      - { label: "غلاف", name: "cover", widget: "image" }
      - { label: "محتوى", name: "body", widget: "markdown" }
